from ...models import ProductImage

product_images = [
    ProductImage(
        product_id=1,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=2,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=3,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=4,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=5,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=6,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=7,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=8,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=9,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=10,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=11,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
    ProductImage(
        product_id=12,
        image='https://vibrato-images.s3.us-west-1.amazonaws.com/default_instrument.png',
    ),
]
