from ...models import Product

products = [
    Product(
        shop_id=1,
        name='American Standard Stratocaster 1978',
        brand='Fender',
        category='Electric Guitar',
        condition='Excellent',
        description='Beautiful instrument, barely used. Needs to be restrung.',
        product_price=125000,
        shipping_price=8000,
        quantity=1,
    ),
    Product(
        shop_id=1,
        name='AC30C2 Tube Combo Amp',
        brand='Vox',
        category='Guitar Combo Amplifier',
        condition='Very Good',
        description='Gorgeous sound, but have a newer one to use for myself. In good condition with a few cosmetic dings.',
        product_price=110000,
        shipping_price=10000,
        quantity=1,
    ),
    Product(
        shop_id=2,
        name='TU-3 Chromatic Tuner',
        brand='BOSS',
        category='Tuning Pedal',
        condition='Mint',
        description='Used a few times. Works like new, no scratches or marks.',
        product_price=5000,
        shipping_price=0,
        quantity=1,
    ),
    Product(
        shop_id=2,
        name='DrumBrute 2017',
        brand='Arturia',
        category='Drum Machine',
        condition='Excellent',
        description='Fantastic sound, but not for my personal taste. Lightly used with no blemishes.',
        product_price=19750,
        shipping_price=3000,
        quantity=1,
    ),
    Product(
        shop_id=3,
        name='MPK Mini MkIII 25-Key MIDI Controller',
        brand='AKAI',
        category='Midi Controller',
        condition='Brand New',
        description='New product, verified distributor.',
        product_price=9900,
        shipping_price=999,
        quantity=6,
    ),
    Product(
        shop_id=3,
        name='314ce Acoustic-Electric Guitar',
        brand='Taylor',
        category='Acoustic Guitar',
        condition='Brand New',
        description='New product, verified distributor.',
        product_price=249900,
        shipping_price=8000,
        quantity=2,
    ),
    Product(
        shop_id=3,
        name='000-15SM Acoustic Guitar',
        brand='Martin',
        category='Acoustic Guitar',
        condition='Brand New',
        description='New product, verified distributor.',
        product_price=197500,
        shipping_price=6000,
        quantity=3,
    ),
    Product(
        shop_id=4,
        name='Special 20 Harmonica - Key of C',
        brand='Hohner',
        category='Harmonica',
        condition='Brand New',
        description='New product, verified distributor.',
        product_price=5499,
        shipping_price=850,
        quantity=3,
    ),
    Product(
        shop_id=4,
        name='microKORG Synthesizer with Vocoder',
        brand='KORG',
        category='Digital Synthesizer',
        condition='Brand New',
        description='New product, verified distributor.',
        product_price=45900,
        shipping_price=0,
        quantity=21,
    ),
    Product(
        shop_id=5,
        name='TLM 103 Large-Diaphragm Condensor Mic',
        brand='Neumann',
        category='Condensor Microphone',
        condition='Brand New',
        description='New product, verified distributor. Heavily irradiated.',
        product_price=119900,
        shipping_price=1950,
        quantity=1,
    ),
    Product(
        shop_id=5,
        name='DL4 MkII',
        brand='Line 6',
        category='Delay Pedal',
        condition='Refurbished',
        description='Refurbished, minimally used. Works like new, no cosmetic damage. Heavily irradiated.',
        product_price=26999,
        shipping_price=1499,
        quantity=1,
    ),
    Product(
        shop_id=5,
        name='KeyStep Pro 37-Key Midi Controller',
        brand='Arturia',
        category='MIDI Controller',
        condition='Brand New',
        description='New product, verified distributor. Heavily irradiated.',
        product_price=45900,
        shipping_price=0,
        quantity=4,
    ),
]
