"""empty message

Revision ID: cffb2bf89046
Revises: 7da48d709d31
Create Date: 2024-06-09 10:07:32.232691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffb2bf89046'
down_revision = '7da48d709d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('add_user_id_to_products', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('add_user_id_to_products', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
